apiVersion : apps/v1
kind: Deployment
metadata:
  name: naveenvasudevanak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naveenvasudevanaks
  template:
    metadata:
      labels:
        app: naveenvasudevanaks 
    spec:
      containers:
        - name: naveenvasudevanaks 
          image: itcadmin.azurecr.io/naveenvasudevanaks
          ports:
          - containerPort: 80
<<<<<<< HEAD

=======
---       
>>>>>>> bfdd6819286de9d26a4c650caa80e254b712a40f
apiVersion: v1
kind: Service
metadata:
    name: naveenvasudevanaks
spec:
    type: LoadBalancer
    ports:
<<<<<<< HEAD
    - port: 80
    selector:
        app: naveenvasudevanaks

=======
    - port: 80 
    selector:
        app: naveenvasudevanaks
          
>>>>>>> bfdd6819286de9d26a4c650caa80e254b712a40f
