apiVersion : apps/v1
kind: Deployment
metadata:
  name: naveenvasudevanak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naveenvasudevanaks
  template:
    metadata:
      labels:
        app: naveenvasudevanaks 
    spec:
      containers:
        - name: naveenvasudevanaks 
          image: itcadmin.azurecr.io/naveenvasudevanaks
          ports:
          - containerPort: 80
          imagePullPolicy: Always
---       
apiVersion: v1
kind: Service
metadata:
    name: naveenvasudevanaks
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: naveenvasudevanaks
    
          

